/* ---------------------------------------------------------------------------
 * VENDORED COPY — DO NOT EDIT THIS FILE.
 *
 * @evalguard/cli — timedFetch, the boundary every verdict command routes through
 *
 * This package does not depend on @evalguard/wrapper-core, so the same-host
 * redirect rule is copied here verbatim instead of imported. Edit the CANONICAL
 * file and re-run `node scripts/same-host-redirect-drift-gate.mjs --write`.
 * The gate fails the build if this copy drifts by so much as one byte.
 * ------------------------------------------------------------------------- */
// @vendored-from packages/wrapper-core/src/same-host-redirect.ts
/**
 * SAME-HOST-ONLY redirect handling for every EvalGuard verdict transport.
 *
 * ─── Why this file exists ───────────────────────────────────────────────────
 *
 * SEC-051 (2026-08-10) closed a real exfiltration hole: WHATWG/undici `fetch`
 * defaults to `redirect: "follow"`, so a 3xx served on the configured endpoint
 * diverted the guardrail call. On 301/302/303 the platform rewrites the request
 * to a bodyless GET, so `checkInput(prompt)` reached the redirect target with
 * the prompt NEVER TRANSMITTED and the target's `{"blocked":false}` came back
 * as a verdict about it. On 307/308 the body IS preserved, so the screened text
 * was re-POSTed verbatim to a host the RESPONSE chose, together with
 * `Authorization: Bearer <the org's API key>`.
 *
 * The fix shipped as a blanket `redirect: "error"` on every verdict fetch. That
 * closes the hole and BREAKS LIVE CUSTOMERS, because production itself emits
 * redirects on the verdict route. Measured against live prod 2026-08-12 with
 * `redirect: "manual"`:
 *
 *   POST https://evalguard.ai/api/v1/firewall/check/     -> 308  Location: /api/v1/firewall/check
 *   POST https://evalguard.ai/api/v1/firewall/check      -> 401  (the honest path; no hop)
 *   POST http://evalguard.ai/api/v1/firewall/check       -> 301  Location: https://evalguard.ai/api/v1/firewall/check
 *   POST https://www.evalguard.ai/api/v1/firewall/check  -> 301  Location: https://evalguard.ai/api/v1/firewall/check
 *   POST http://www.evalguard.ai/api/v1/firewall/check   -> 301  Location: https://www.evalguard.ai/api/v1/firewall/check
 *
 * A blanket refusal turns each of those into a hard-failing guardrail on the
 * customer's next upgrade — fail-CLOSED, which is the safe direction, but it
 * stops their traffic in a PATCH release.
 *
 * ─── The rule ───────────────────────────────────────────────────────────────
 *
 * FOLLOW when the target HOST is unchanged. REFUSE when it changes at all.
 *
 *  1. No `Location` on a 3xx                     -> REFUSE
 *  2. `Location` that will not parse             -> REFUSE
 *  3. Target scheme not http/https               -> REFUSE
 *  4. Target host (INCLUDING PORT) differs       -> REFUSE   <- the whole control
 *  5. https -> http on the same host             -> REFUSE   (downgrade)
 *  6. More than {@link MAX_REDIRECT_HOPS} hops   -> REFUSE   (a loop must terminate)
 *  7. A body that cannot be replayed             -> REFUSE
 *
 * Rule 4 compares `URL.host`, which INCLUDES a non-default port, and never the
 * hostname alone. Go's stdlib `shouldCopyHeaderOnRedirect` compares hostname
 * only, and that is precisely how the 2026-08-10 measurement got the API key
 * forwarded to a same-hostname/different-port listener. The comparison is also
 * why the hop loop is written here rather than delegated to the platform: no
 * runtime's built-in follower implements this rule, and three of them
 * (WHATWG fetch, python-requests, net/http) implement a WRONG one.
 *
 * ─── Deliberate deviation from RFC 9110 §15.4 ───────────────────────────────
 *
 * On a FOLLOW this re-issues the ORIGINAL method and body for EVERY 3xx code,
 * including 301/302/303 — where the spec (and every runtime) downgrades a POST
 * to a bodyless GET. That downgrade IS the original defect: it produces a
 * verdict about text that was never sent. The target is the same host we
 * already authenticated to and already sent the body to, so re-transmitting it
 * is not an exfiltration; silently dropping it is a fail-open.
 *
 * ─── The customer this still breaks, on purpose ─────────────────────────────
 *
 * `www.evalguard.ai` -> `evalguard.ai` IS a host change and IS refused. A
 * customer whose base URL uses the `www.` host gets a hard-failing guardrail.
 * That is correct: a host change is exactly the vector. It is NOT widened to
 * "same registrable domain" — `evalguard.ai` and `www.evalguard.ai` share a
 * registrable domain, and so would any subdomain an attacker who can add a DNS
 * record or take over a dangling CNAME controls. See the release notes.
 *
 * This module has NO imports and no runtime dependencies on purpose: it is
 * copied verbatim into the packages that cannot depend on
 * `@evalguard/wrapper-core`, and `scripts/same-host-redirect-drift-gate.mjs`
 * fails the build if any copy drifts from this one.
 */

/**
 * Maximum redirects followed before refusing.
 *
 * Three, not the platform default of 20. Every legitimate hop on this transport
 * is a normalisation the origin performs on hop 1 (a trailing-slash 308, an
 * http->https 301). Two chained normalisations is already unusual; a third is
 * the ceiling, and anything past it is a loop. A same-host redirect loop must
 * TERMINATE rather than park the caller's request handler — `checkInput` sits
 * on the customer's hot path.
 */
export const MAX_REDIRECT_HOPS = 3;

/** Stable machine code for every refusal in this module. */
export const REDIRECT_REFUSED_CODE = "REDIRECT_REFUSED" as const;

/** Why a hop was refused. Kept as a closed union so every reason is testable. */
export type RedirectRefusalReason =
  | "host-change"
  | "scheme-downgrade"
  | "unsupported-scheme"
  | "missing-location"
  | "unparsable-location"
  | "too-many-hops"
  | "non-replayable-body"
  | "opaque-redirect";

/**
 * Raised instead of following a hop. Never caught-and-defaulted inside this
 * module: the point is that it escapes to the transport, whose existing
 * fail-CLOSED path turns it into a denied verdict.
 */
export class RedirectRefusedError extends Error {
  readonly code = REDIRECT_REFUSED_CODE;
  readonly reason: RedirectRefusalReason;
  readonly status: number;
  readonly fromHost: string;
  readonly toHost: string;

  constructor(
    message: string,
    detail: {
      reason: RedirectRefusalReason;
      status: number;
      fromHost: string;
      toHost: string;
    },
  ) {
    super(message);
    this.name = "RedirectRefusedError";
    this.reason = detail.reason;
    this.status = detail.status;
    this.fromHost = detail.fromHost;
    this.toHost = detail.toHost;
  }
}

/** Is this the error this module raises? Cheap, cross-realm-safe check. */
export function isRedirectRefused(e: unknown): e is RedirectRefusedError {
  return (
    e !== null &&
    typeof e === "object" &&
    (e as { code?: unknown }).code === REDIRECT_REFUSED_CODE
  );
}

/**
 * Structural stand-ins for `HeadersInit` / `BodyInit` / `RequestInit`.
 *
 * Those three names are DOM-lib globals. `@evalguard/otel-sdk` compiles with
 * `lib: ["ES2022"]` and no DOM, so naming them here would break one of the four
 * packages this file is copied into — and a security control that has to be
 * hand-edited per copy is the drift this file's gate exists to prevent. Only
 * `fetch`, `Response` and `AbortSignal`, which every target has, are referenced
 * by their global names.
 */
export type HeadersLike =
  | Record<string, string>
  | ReadonlyArray<ReadonlyArray<string>>
  | { forEach(cb: (value: string, name: string) => void): void };

/** The subset of `RequestInit` this module reads; extra keys pass through. */
export interface SameHostRequestInit {
  method?: string;
  headers?: HeadersLike;
  body?: unknown;
  signal?: AbortSignal | null;
}

/** `fetch`'s own init type, whatever the ambient lib calls it. */
type PlatformRequestInit = NonNullable<Parameters<typeof fetch>[1]>;

/**
 * Request headers that authenticate the caller and must therefore never cross a
 * host boundary. Lowercase; matched case-insensitively, and `x-evalguard-` is
 * matched as a PREFIX so a header added later is covered by default.
 */
const CREDENTIAL_HEADERS = ["authorization", "cookie", "x-api-key", "proxy-authorization"];
const CREDENTIAL_HEADER_PREFIX = "x-evalguard-";

function isCredentialHeader(name: string): boolean {
  const lower = name.toLowerCase();
  return CREDENTIAL_HEADERS.includes(lower) || lower.startsWith(CREDENTIAL_HEADER_PREFIX);
}

/**
 * The headers to send on the NEXT hop.
 *
 * Unchanged when the host is unchanged. When the host CHANGES, every credential
 * header is deleted.
 *
 * `followSameHostRedirects` refuses a host change outright, so the stripping
 * branch is not reachable through it today — which is exactly why it is written
 * as an explicit, exported, directly-tested function and called on the LIVE
 * path rather than left to the HTTP library. Go was MEASURED to strip
 * `Authorization` across hosts and Python inherits `requests`' stripping, but
 * neither is a control this SDK owns: Go's own comparison ignores the port, and
 * a library default can change under us. If someone later widens the host rule,
 * this control is already in place instead of being remembered.
 */
export function headersForHop(
  headers: HeadersLike | undefined,
  from: URL,
  to: URL,
): HeadersLike | undefined {
  if (headers === undefined) return undefined;
  if (from.host === to.host) return headers;

  const kept: Record<string, string> = {};
  forEachHeader(headers, (name, value) => {
    if (!isCredentialHeader(name)) kept[name] = value;
  });
  return kept;
}

/** Iterate any headers shape without depending on the `Headers` class. */
function forEachHeader(
  headers: HeadersLike,
  visit: (name: string, value: string) => void,
): void {
  if (Array.isArray(headers)) {
    for (const pair of headers as ReadonlyArray<ReadonlyArray<string>>) {
      visit(String(pair[0] ?? ""), String(pair[1] ?? ""));
    }
    return;
  }
  const maybeIterable = headers as { forEach?: (cb: (v: string, k: string) => void) => void };
  if (typeof maybeIterable.forEach === "function") {
    // A real `Headers` instance: forEach yields (value, name).
    maybeIterable.forEach((value, name) => visit(name, value));
    return;
  }
  for (const [name, value] of Object.entries(headers as Record<string, string>)) {
    visit(name, String(value));
  }
}

/**
 * Bodies this module is willing to re-transmit on a hop.
 *
 * A `ReadableStream` (or an async iterable, which undici also accepts) is
 * consumed by the first attempt and cannot be replayed, so following would send
 * an EMPTY body — the same "verdict about text that was never transmitted"
 * defect by another route. Refuse instead.
 */
function isReplayableBody(body: unknown): boolean {
  if (body === null || body === undefined) return true;
  if (typeof body === "string") return true;
  if (body instanceof ArrayBuffer) return true;
  if (ArrayBuffer.isView(body)) return true;
  if (typeof URLSearchParams !== "undefined" && body instanceof URLSearchParams) return true;
  if (typeof Blob !== "undefined" && body instanceof Blob) return true;
  if (typeof FormData !== "undefined" && body instanceof FormData) return true;
  return false;
}

/**
 * Resolve and VET a redirect target. Throws {@link RedirectRefusedError} unless
 * the hop is a same-host, non-downgrading http(s) hop.
 *
 * Exported so the rule can be unit-tested directly, hop by hop, without
 * standing up a listener — and so a reviewer can read the whole control in one
 * function.
 */
export function resolveSameHostRedirect(
  from: URL,
  location: string | null | undefined,
  status: number,
  label: string,
): URL {
  const fromHost = from.host;

  if (location === null || location === undefined || location.trim() === "") {
    throw new RedirectRefusedError(
      `EvalGuard ${label} answered HTTP ${status} (a redirect) with no Location header, so there ` +
        `is nothing to follow and no result to read. Treated as INDETERMINATE (deny), never as ` +
        `an allow.`,
      { reason: "missing-location", status, fromHost, toHost: "" },
    );
  }

  let to: URL;
  try {
    to = new URL(location, from);
  } catch {
    throw new RedirectRefusedError(
      `EvalGuard ${label} answered HTTP ${status} with a Location that is not a usable URL, so ` +
        `the hop could not be vetted. Treated as INDETERMINATE (deny), never as an allow.`,
      { reason: "unparsable-location", status, fromHost, toHost: "" },
    );
  }

  if (to.protocol !== "https:" && to.protocol !== "http:") {
    throw new RedirectRefusedError(
      `EvalGuard ${label} answered HTTP ${status} redirecting to a "${to.protocol}" URL. Only ` +
        `http and https hops are followed. Treated as INDETERMINATE (deny).`,
      { reason: "unsupported-scheme", status, fromHost, toHost: to.host },
    );
  }

  if (to.host !== fromHost) {
    throw new RedirectRefusedError(
      `EvalGuard ${label} answered HTTP ${status} redirecting from host "${fromHost}" to a ` +
        `DIFFERENT host "${to.host}", which EvalGuard refuses to follow. Following it would send ` +
        `your content — and your API key — to a host chosen by the response, and return that ` +
        `host's answer as an EvalGuard verdict. Same-host redirects (a trailing-slash 308, an ` +
        `http->https upgrade) ARE followed. If this is your own deployment, set ` +
        `EVALGUARD_BASE_URL to the host that actually serves the API (note: "www.evalguard.ai" ` +
        `redirects to "evalguard.ai" and is a HOST CHANGE — use https://evalguard.ai/api/v1). ` +
        `Treated as INDETERMINATE (deny), never as an allow.`,
      { reason: "host-change", status, fromHost, toHost: to.host },
    );
  }

  if (from.protocol === "https:" && to.protocol === "http:") {
    throw new RedirectRefusedError(
      `EvalGuard ${label} answered HTTP ${status} redirecting from https to PLAINTEXT http on ` +
        `"${to.host}". Following it would put your API key and the text being screened on the ` +
        `wire in the clear. Treated as INDETERMINATE (deny), never as an allow.`,
      { reason: "scheme-downgrade", status, fromHost, toHost: to.host },
    );
  }

  return to;
}

/** Options for {@link followSameHostRedirects}. */
export interface SameHostRedirectOptions {
  /** Injected transport, for tests and for callers that wrap `fetch`. */
  fetchImpl?: typeof fetch;
  /** Hop ceiling; defaults to {@link MAX_REDIRECT_HOPS}. */
  maxHops?: number;
  /** Human label used in refusal messages, e.g. `POST /firewall/check`. */
  label?: string;
}

/**
 * `fetch` that follows SAME-HOST redirects and refuses every other kind.
 *
 * `redirect: "manual"` is spread LAST so a caller cannot pass `redirect` and
 * win — order is the control, exactly as `redirect: "error"` was ordered before
 * it. `"manual"` on its own would be strictly WORSE than the old blanket
 * refusal (an un-followed 3xx is a normal Response whose `!res.ok` branch a
 * caller can misread), which is why it never appears without this loop and why
 * `scripts/verdict-redirect-gate.mjs` refuses to count it as a posture on its
 * own.
 */
export async function followSameHostRedirects(
  input: string | URL,
  init: SameHostRequestInit = {},
  opts: SameHostRedirectOptions = {},
): Promise<Response> {
  const fetchImpl = opts.fetchImpl ?? fetch;
  const maxHops = opts.maxHops ?? MAX_REDIRECT_HOPS;
  const label = opts.label ?? String(input);

  let current = input instanceof URL ? new URL(input.href) : new URL(String(input));
  let headers = init.headers;

  for (let hop = 0; ; hop++) {
    // `redirect: "manual"` is spread LAST so a caller that passes `redirect`
    // cannot win. The cast is to the ambient lib's own init type — see the note
    // on `PlatformRequestInit`; the object is structurally a RequestInit.
    const res = await fetchImpl(current.href, {
      ...init,
      headers,
      redirect: "manual",
    } as PlatformRequestInit);

    // Only a NUMERIC status in [300,400) is a redirect. Written as a positive
    // test rather than `status < 300 || status >= 400`, because that form
    // classifies a response with NO readable status as a redirect: `undefined`
    // is neither `< 300` nor `>= 400`, so it fell through into the hop logic and
    // was refused as "a 3xx with no Location". Four suites' partial `fetch`
    // doubles (`{ ok: true, json }`) hit exactly that. This function's job is
    // REDIRECTS; deciding whether an unreadable response is a result belongs to
    // the transports' own status gates, which already refuse it — moving that
    // judgement here would silently change behaviour for every non-redirect
    // shape as a side effect of a redirect fix.
    const status = (res as { status?: unknown }).status;
    const isRedirect = typeof status === "number" && status >= 300 && status < 400;
    if (!isRedirect) return res;

    // Browsers answer a `manual` redirect with an OPAQUE filtered response:
    // `type === "opaqueredirect"`, status 0, no readable headers. There is no
    // way to vet a hop we cannot see, so it is refused. (Node/undici, where
    // every wrapper actually runs, returns the real 3xx with its headers.)
    if ((res as { type?: string }).type === "opaqueredirect" || res.status === 0) {
      throw new RedirectRefusedError(
        `EvalGuard ${label} was redirected, but this runtime hides the redirect target from the ` +
          `page (an opaque redirect), so EvalGuard cannot verify it stays on the same host and ` +
          `refuses to follow it. Point EVALGUARD_BASE_URL at the exact origin that serves the ` +
          `API. Treated as INDETERMINATE (deny), never as an allow.`,
        { reason: "opaque-redirect", status: res.status, fromHost: current.host, toHost: "" },
      );
    }

    if (hop >= maxHops) {
      throw new RedirectRefusedError(
        `EvalGuard ${label} redirected more than ${maxHops} times on host "${current.host}" ` +
          `without answering. A redirect loop cannot produce a verdict, and following it further ` +
          `would park this call. Treated as INDETERMINATE (deny), never as an allow.`,
        { reason: "too-many-hops", status: res.status, fromHost: current.host, toHost: current.host },
      );
    }

    if (!isReplayableBody(init.body)) {
      throw new RedirectRefusedError(
        `EvalGuard ${label} answered HTTP ${res.status} (a redirect), but this request's body is ` +
          `a stream that has already been consumed and cannot be re-sent. Following would deliver ` +
          `an EMPTY body and return a verdict about nothing. Treated as INDETERMINATE (deny).`,
        {
          reason: "non-replayable-body",
          status: res.status,
          fromHost: current.host,
          toHost: current.host,
        },
      );
    }

    const next = resolveSameHostRedirect(current, res.headers.get("location"), res.status, label);

    // Same-host by construction, so this returns `headers` untouched. Called on
    // the live path anyway — see the docblock on headersForHop.
    headers = headersForHop(headers, current, next);
    current = next;

    // The body is NOT dropped and the method is NOT downgraded, for any 3xx
    // code. See the RFC-deviation note at the top of this file: the downgrade
    // to a bodyless GET is the defect, and the target is the same host.
    //
    // Draining the un-followed response keeps undici from holding the socket.
    const drain = (res as { body?: { cancel?: () => Promise<void> } | null }).body?.cancel?.();
    void drain?.catch(() => {});
  }
}
